---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucedd-dev
data:
  ucedd-dir.conf: |-
    <Directory /var/www/html/ucedd-dashboard>
        # Unset X-Frame-Options to allow framing
        Header unset X-Frame-Options

        # Lock down asset sources and sites that can frame the page using CSP
        # TODO: This will be simpler if we host most assets ourselves
        # FIXME: vue.global.js is necessitating use of `script-src 'unsafe-eval'`; build with Vite instead
        Header set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' https://code.jquery.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com/ajax/libs/PapaParse/ https://cdn.datatables.net/v/bs5/ https://unpkg.com/vue@3/; style-src 'self' https://cdn.jsdelivr.net https://cdn.datatables.net/v/bs5/; img-src 'self' data:; frame-ancestors 'self' https://*.ohsu.edu"
    </Directory>
