---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucedd-dev
data:
  ucedd-dir.conf: |-
    <Directory /var/www/html/ucedd-dashboard>
        # Unset X-Frame-Options to allow framing
        Header unset X-Frame-Options

        # Lock down asset sources and sites that can frame the page using CSP
        Header set Content-Security-Policy "default-src 'self'; script-src 'self' https://code.jquery.com https://cdn.jsdelivr.net; style-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; frame-ancestors 'self' https://*.ohsu.edu"
    </Directory>
