apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucedd-dev
spec:
  selector:
    matchLabels:
      app: ucedd-dev
  template:
    metadata:
      labels:
        app: ucedd-dev
    spec:
      containers:
      - name: apache
        image: octri.ohsu.edu/apache:2.4-k8s
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 1000m
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: octrikube-nfs
          mountPath: /var/www/html
          subPath: ucedd-dashboard-dev
        - name: ucedd-directory-conf
          mountPath: /etc/httpd/conf.local.d
      - name: apache-sidecar
        image: octri.ohsu.edu/apache_sidecar:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9117
          name: apache-exporter
        envFrom:
        - secretRef:
            name: ucedd-dev
        command:
        - /usr/bin/prometheus-apache-exporter
        - --scrape_uri="http://localhost/_stats?auto"
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
          limits:
            memory: 64Mi
            cpu: 10m
        volumeMounts:
        - name: octrikube-nfs
          mountPath: /workdir/webroot
          subPath: ucedd-dashboard-dev
      volumes:
      - name: octrikube-nfs
        persistentVolumeClaim:
          claimName: octrikube-nfs
      - name: ucedd-directory-conf
        configMap:
          name: ucedd-dev
          items:
          - key: ucedd-dir.conf
            path: ucedd-dir.conf
            mode: 420 # 0644
      imagePullSecrets:
      - name: octri-registry-cred